%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1        
num_of_cam: 2  

imu_topic: "/camera/imu"
image0_topic: "/camera/fisheye1/image_raw"
image1_topic: "/camera/fisheye2/image_raw"
output_path: "/home/dji/output/"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 848
image_height: 800
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ -0.99996986,  0.00618137,  0.00469777,  0.01856476,
#        -0.00617392, -0.99997966,  0.00159856,  0.00738497,
#        0.00470756,  0.00156951,  0.99998769,  0.00300114,
#         0., 0., 0., 1. ]

# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ -0.99997589,  0.00685624, -0.00109737, -0.04544379,
#        -0.00686319, -0.99995555,  0.0064646,   0.00707597,
#        -0.001053,    0.00647197,  0.9999785,   0.00302865, 
#        0., 0., 0., 1. ]

# t265-4
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -0.99994915,  0.00703838,  0.00722229,  0.01675421,
       -0.00703725, -0.99997522,  0.00018229,  0.00868688,
       0.00722339,  0.00013145,  0.9999739,   0.00459863,
        0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -0.99996908,  0.0077322,   0.00143501, -0.04724913,
       -0.0077251,  -0.99995822,  0.00488742,  0.00826312,
       0.00147275,  0.00487619,  0.99998703,  0.00481171, 
       0., 0., 0., 1. ]


#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0       # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.0190007943382           # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.00186944416638         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.000581142281694         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 2.34080857076e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.7833         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.00302397567801                            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/chao/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
